### ISSUE TITLE
Hackage bugfix release

### ISSUE THREAD

**Issue by xsebek** [colinhect/hsnoise#3]
Hi, could you please make a new release on Hackage with the bug fix?

We recently released Swarm 0.1 which uses `hsnoise` and negative coordinates.

Locally we use `source-repository-package` to get the bug fix, but with the Hackage release we get the old `hsnoise` version:
- swarm-game/swarm#745

Thanks for making `hsnoise`, we really like how simple it is to use! :+1:

**Comment by colinhect** [comment]
Glad to hear you are finding the library useful. Yes, I can publish a new release on Hackage.

**Comment by colinhect** [comment]
Posted version 0.0.3 on Hackage: https://hackage.haskell.org/package/hsnoise-0.0.3

Let me know if I messed anything up in the package. It has been many years since publishing a Haskell package.

Thanks,
Colin

**Comment by byorgey** [comment]
@colinhect looks like it works great, thanks!
